using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Parsing
{
    public static class CheckPointParsing2233
    {
        public static bool Point22(Parsing form1, JArray jsonArray)
        {
            TextBox msgBox = form1.GetMessageBox();
            try
            {
                bool eventsGeneratedByStateModels = false;
                bool eventsGeneratedByExternalEntities = false;

                foreach (var subsystem in jsonArray)
                {
                    if (subsystem["model"] is JArray model)
                    {
                        foreach (var element in model)
                        {
                            var elementType = element["type"]?.ToString();

                            // Check state models for events
                            if (elementType == "class" && element["states"] is JArray states)
                            {
                                foreach (var state in states)
                                {
                                    var stateEvents = state["state_event"] as JArray;
                                    if (stateEvents != null && stateEvents.Count > 0)
                                    {
                                        eventsGeneratedByStateModels = true;
                                        break;
                                    }
                                }
                            }

                            // Check external entities for events
                            if (elementType == "external_entity")
                            {
                                var externalEvents = element["events"] as JArray;
                                if (externalEvents != null && externalEvents.Count > 0)
                                {
                                    eventsGeneratedByExternalEntities = true;
                                }
                            }
                        }
                    }
                }

                if (!eventsGeneratedByStateModels)
                {
                    msgBox.AppendText("Syntax error 22: No events generated by state models.\r\n");
                    return false;
                }

                if (!eventsGeneratedByExternalEntities)
                {
                    msgBox.AppendText("Syntax error 22: No events generated by external entities.\r\n");
                    return false;
                }

                msgBox.AppendText("Success 22: Events are correctly generated by state models and external entities.\r\n");
                return true;
            }
            catch (Exception ex)
            {
                msgBox.AppendText("Syntax error 22: " + ex.Message + "\r\n");
                return false;
            }
        }

        public static bool Point31(Parsing form1, JArray jsonArray)
        {
            TextBox msgBox = form1.GetMessageBox();
            try
            {
                HashSet<string> entitiesWithEvents = new HashSet<string>();

                // Loop through subsystems and model elements
                foreach (var subsystem in jsonArray)
                {
                    if (subsystem["model"] is JArray model)
                    {
                        foreach (var element in model)
                        {
                            var elementType = element["type"]?.ToString();

                            // Check state models
                            if (elementType == "class" && element["states"] is JArray states)
                            {
                                var className = element["class_name"]?.ToString();
                                if (states.Any(state => (state["state_event"] as JArray)?.Count > 0))
                                {
                                    entitiesWithEvents.Add(className);
                                }
                            }

                            // Check external entities
                            if (elementType == "external_entity" && element["events"] is JArray events)
                            {
                                var entityName = element["entity_name"]?.ToString();
                                if (events.Count > 0)
                                {
                                    entitiesWithEvents.Add(entityName);
                                }
                            }
                        }
                    }
                }

                // Check if entities with events are present in Object Communication Model
                foreach (var subsystem in jsonArray)
                {
                    if (subsystem["OCM"] is JArray ocm)
                    {
                        foreach (var element in ocm)
                        {
                            var elementName = element["name"]?.ToString();
                            if (entitiesWithEvents.Contains(elementName))
                            {
                                entitiesWithEvents.Remove(elementName);
                            }
                        }
                    }
                }

                if (entitiesWithEvents.Count > 0)
                {
                    msgBox.AppendText("Syntax error 31: The following entities with events are missing from the Object Communication Model: " + string.Join(", ", entitiesWithEvents) + "\r\n");
                    return false;
                }

                msgBox.AppendText("Success 31: All entities with events are correctly listed in the Object Communication Model.\r\n");
                return true;
            }
            catch (Exception ex)
            {
                msgBox.AppendText("Syntax error 31: " + ex.Message + "\r\n");
                return false;
            }
        }

        public static bool Point32(Parsing form1, JArray jsonArray)
        {
            TextBox msgBox = form1.GetMessageBox();
            try
            {
                HashSet<string> eventsInvolved = new HashSet<string>();

                // Loop through subsystems and model elements
                foreach (var subsystem in jsonArray)
                {
                    if (subsystem["model"] is JArray model)
                    {
                        foreach (var element in model)
                        {
                            var elementType = element["type"]?.ToString();

                            // Check external entities for events
                            if (elementType == "external_entity" && element["events"] is JArray events)
                            {
                                foreach (var evt in events)
                                {
                                    var eventName = evt["event_name"]?.ToString();
                                    eventsInvolved.Add(eventName);
                                }
                            }

                            // Check state models for events
                            if (elementType == "class" && element["states"] is JArray states)
                            {
                                foreach (var state in states)
                                {
                                    var stateEvents = state["state_event"] as JArray;
                                    if (stateEvents != null)
                                    {
                                        foreach (var eventName in stateEvents)
                                        {
                                            eventsInvolved.Add(eventName.ToString());
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                // Check if events involved are present in Object Communication Model (OCM)
                foreach (var subsystem in jsonArray)
                {
                    if (subsystem["OCM"] is JArray ocm)
                    {
                        foreach (var element in ocm)
                        {
                            var elementEvents = element["events"] as JArray;
                            if (elementEvents != null)
                            {
                                foreach (var evt in elementEvents)
                                {
                                    var eventName = evt.ToString();
                                    if (eventsInvolved.Contains(eventName))
                                    {
                                        eventsInvolved.Remove(eventName);
                                    }
                                }
                            }
                        }
                    }
                }

                if (eventsInvolved.Count > 0)
                {
                    msgBox.AppendText("Syntax error 32: The following events are missing from the Object Communication Model: " + string.Join(", ", eventsInvolved) + "\r\n");
                    return false;
                }

                msgBox.AppendText("Success 32: All involved events are correctly listed in the Object Communication Model.\r\n");
                return true;
            }
            catch (Exception ex)
            {
                msgBox.AppendText("Syntax error 32: " + ex.Message + "\r\n");
                return false;
            }
        }

        public static bool Point33(Parsing form1, JArray jsonArray)
        {
            TextBox msgBox = form1.GetMessageBox();
            try
            {
                bool timerFound = false;
                HashSet<string> timerEvents = new HashSet<string>();

                // Identify TIMER state model and related events
                foreach (var subsystem in jsonArray)
                {
                    if (subsystem["model"] is JArray model)
                    {
                        foreach (var element in model)
                        {
                            var elementType = element["type"]?.ToString();

                            // Check for TIMER state model
                            if (elementType == "class" && element["class_name"]?.ToString() == "TIMER")
                            {
                                timerFound = true;

                                // Check for events associated with TIMER
                                var states = element["states"] as JArray;
                                if (states != null)
                                {
                                    foreach (var state in states)
                                    {
                                        var stateEvents = state["state_event"] as JArray;
                                        if (stateEvents != null)
                                        {
                                            foreach (var evt in stateEvents)
                                            {
                                                timerEvents.Add(evt.ToString());
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                // Check if TIMER and its events are present in Object Communication Model (OCM)
                foreach (var subsystem in jsonArray)
                {
                    if (subsystem["OCM"] is JArray ocm)
                    {
                        foreach (var element in ocm)
                        {
                            var elementName = element["name"]?.ToString();
                            if (elementName == "TIMER" || timerEvents.Contains(elementName))
                            {
                                msgBox.AppendText("Syntax error 33: The TIMER state model or its events are shown on the Object Communication Model (OCM).\r\n");
                                return false;
                            }
                        }
                    }
                }

                if (!timerFound)
                {
                    msgBox.AppendText("Syntax error 33: The TIMER state model is not found in the model.\r\n");
                    return false;
                }

                msgBox.AppendText("Success 33: The TIMER state model and its events are not shown on the Object Communication Model (OCM).\r\n");
                return true;
            }
            catch (Exception ex)
            {
                msgBox.AppendText("Syntax error 33: " + ex.Message + "\r\n");
                return false;
            }
        }

    }
}
